### ISSUE TITLE
"(node:10092) ExperimentalWarning: The ESM module loader is experimental error." when running npm run dev

### ISSUE THREAD

**Issue by Gunsch-NP-23** [peternav2/SWE-Project#1]
```
(node:10092) ExperimentalWarning: The ESM module loader is experimental.
file:///C:/Users/FLGWO/Desktop/NEW_PALTZ_CLASSES/SPRING23/CPS353/SWE-Project/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

    at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code ELIFECYCLE
```

**Comment by Gunsch-NP-23** [comment]
FYI if anyone gets an console error like this when trying to start up localhost/dev server then reinstalling a clean version of Node should fix it. (I was on version 12).
